apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl: 
    manifests: 
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: fatihsevban/ecommerce-auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        infer: 
          - '**/*'

    - image: fatihsevban/ecommerce-product
      context: product
      docker:
        dockerfile: Dockerfile
      sync:
        infer: 
          - '**/*'
          
    - image: fatihsevban/ecommerce-frontend
      context: frontend
      docker:
        dockerfile: Dockerfile
      sync:
        infer: 
          - '**/*'
        